### ISSUE TITLE
can't seem to make repo2docker run 

### ISSUE THREAD

**Issue by lwasser** [earthlab/earth-analytics-python-env#18]
hey @betatim there is something fundamental that i'm struggling w still with repo2docker. 
i just think it's not working properly on my computer. i'll let you work but if at any point if you have an idea as to why i've not been able to get this to run, please let me know. I'm getting a different error than i was prior
```
cu-biot-seec2-172:0-python lewa8222$ git clone https://github.com/earthlab/earth-analytics-python-env.git
Cloning into 'earth-analytics-python-env'...
remote: Counting objects: 54, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 54 (delta 28), reused 19 (delta 9), pack-reused 0
Unpacking objects: 100% (54/54), done.
cu-biot-seec2-172:0-python lewa8222$ cd earth-analytics-python-env/
cu-biot-seec2-172:earth-analytics-python-env lewa8222$ ls
Dockerfile	README.md	environment.yml
cu-biot-seec2-172:earth-analytics-python-env lewa8222$ jupyter-repo2docker https://github.com/earthlab/earth-analytics-python-env.git
Cloning into '/var/folders/43/4q82487d5xsfpxdx6nl_c1wmhckx08/T/repo2dockerr8_am1em'...
remote: Counting objects: 54, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 54 (delta 28), reused 19 (delta 9), pack-reused 0
Unpacking objects: 100% (54/54), done.
Using DockerBuildPack builder
Step 1/6 : FROM jupyter/scipy-notebook
Get https://registry-1.docker.io/v2/jupyter/scipy-notebook/manifests/latest: unauthorized: incorrect username or passwordcu-biot-seec2-172:earth-analytics-python-env lewa8222$ ls
Dockerfile	README.md	environment.yml
cu-biot-seec2-172:earth-analytics-python-env lewa8222$ jupyter-repo2docker https://github.com/jakevdp/PythonDataScienceHandbook
Cloning into '/var/folders/43/4q82487d5xsfpxdx6nl_c1wmhckx08/T/repo2dockernwswssvh'...
remote: Counting objects: 1623, done.
remote: Total 1623 (delta 0), reused 0 (delta 0), pack-reused 1623
Receiving objects: 100% (1623/1623), 96.08 MiB | 20.32 MiB/s, done.
Resolving deltas: 100% (1139/1139), done.
Using PythonBuildPack builder
Step 1/31 : FROM buildpack-deps:artful
Get https://registry-1.docker.io/v2/library/buildpack-deps/manifests/artful: unauthorized: incorrect username or passwordcu-biot-seec2-172:earth-analytics-python-env lewa8222$ 
```

**Comment by betatim** [comment]
That is a weird error to get. All the images used by `repo2docker` are public, not sure why it tries to login. It seems to be a frequent problem though. https://github.com/docker/hub-feedback/issues/1098 suggests to run `docker logout` to fix the problem and to make sure you use your user ID not email address when running `docker login`.

I'd try: `docker logout` and then `repo2docker https://github.com/binder-examples/requirements`.

As far as I know Jake's Data science handbook currently doesn't build because of something to do with the numpy version pinned in the `requirements.txt` and no one has gotten around to fixing that.

**Comment by betatim** [comment]
One more thing: `jupyter-repo2docker https://github.com/earthlab/earth-analytics-python-env.git` will end up using the `Dockerfile` defined in the repository. This is because `repo2docker` will see that there is a `Dockerfile` in the repository which overrides everything else. Kinda explained here: https://mybinder.readthedocs.io/en/latest/using.html#dockerfile (but confusingly enough not in the repo2docker documentation).
